---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: bridge-metrics
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      strimzi.io/kind: KafkaBridge
  namespaceSelector:
    matchNames:
      - metrics-test-0
      - metrics-test-1
  podMetricsEndpoints:
  - path: /metrics
    port: rest-api-mgmt
